CREATE DATABASE WTC;
USE WTC;

CREATE TABLE USUARIO (
ID_USUARIO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOMBRES VARCHAR (20) NOT NULL,
APELLIDO_P VARCHAR (20) NOT NULL,
APELLIDO_M VARCHAR (20) NOT NULL,
NACIMIENTO DATE  NOT NULL,
GENERO ENUM ('M', 'F') NOT NULL,
NACIONALIDAD VARCHAR (20) NOT NULL,
PAIS_ORIGEN VARCHAR (20) NOT NULL,
CORREO VARCHAR (30) NOT NULL,
CONTRASENNA VARCHAR (30) NOT NULL,
TIPO_USUARIO ENUM ('ADMIN','USUARIO') NOT NULL
);
ALTER TABLE USUARIO ADD COLUMN GOOGLE_ID VARCHAR(255) UNIQUE NULL AFTER CORREO;
ALTER TABLE USUARIO MODIFY CONTRASENNA VARCHAR(255) NOT NULL;

CREATE TABLE MULTIMEDIA (
ID_MULTIMEDIA INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
ARCHIVO BLOB NOT NULL

);

CREATE TABLE MUNDIAL(
ID_MUNDIAL INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR (50) NOT NULL,
ANNO VARCHAR (10) NOT NULL,
SEDE VARCHAR (50) NOT NULL,
DESCRIPCION TEXT NOT NULL,
LOGO BLOB NOT NULL,
MASCOTA_NOMBRE VARCHAR (30) NOT NULL,
MASCOTA_IMAGEN BLOB NOT NULL

);

USE WTC;


CREATE TABLE CATEGORIA (
ID_CATEGORIA INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR (30) NOT NULL

);

CREATE TABLE PUBLICACION (
ID_PUBLICACION INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
TITULO VARCHAR (50) NOT NULL,
CONTENIDO TEXT NOT NULL,
FECHA_APROBACION DATE NOT NULL,
FECHA_PUBLICACION DATE NOT NULL,
ESTATUS ENUM ('APROBADA', 'RECHAZADA'),
MULTIMEDIA INT,
USUARIO INT,
MUNDIAL INT,
CATEGORIA INT,

FOREIGN KEY (USUARIO) REFERENCES USUARIO (ID_USUARIO),
FOREIGN KEY (MULTIMEDIA) REFERENCES MULTIMEDIA (ID_MULTIMEDIA),
FOREIGN KEY (MUNDIAL) REFERENCES MUNDIAL  (ID_MUNDIAL),
FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA (ID_CATEGORIA)
);

CREATE TABLE COMENTARIOS (
ID_COMENTARIO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
CONTENIDO TEXT NOT NULL,
USUARIO INT NOT NULL,
PUBLICACION INT NOT NULL,

FOREIGN KEY (USUARIO) REFERENCES USUARIO (ID_USUARIO),
FOREIGN KEY (PUBLICACION) REFERENCES PUBLICACION (ID_PUBLICACION)
);


CREATE TABLE LIKES (
USUARIO INT NOT NULL,
PUBLICACION INT NOT NULL,

FOREIGN KEY (USUARIO) REFERENCES USUARIO (ID_USUARIO),
FOREIGN KEY (PUBLICACION) REFERENCES PUBLICACION (ID_PUBLICACION),
PRIMARY KEY (USUARIO, PUBLICACION)

);

USE WTC;
CREATE TABLE MUNDIAL_EQUIPOS (
    ID_MUNDIAL INT NOT NULL,
    ID_EQUIPO INT NOT NULL,
    PRIMARY KEY (ID_MUNDIAL, ID_EQUIPO),
    FOREIGN KEY (ID_MUNDIAL) REFERENCES MUNDIAL(ID_MUNDIAL),
    FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);
CREATE TABLE EQUIPO (
    ID_EQUIPO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE multimedia_mundial (
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    multimedia_id INT(11) NOT NULL,
    mundial_id INT(11) NOT NULL,
    es_banner TINYINT(1) DEFAULT 0,
    es_copa TINYINT(1) DEFAULT 0,
    es_mascota TINYINT(1) DEFAULT 0,

    CONSTRAINT fk_mm_multimedia 
        FOREIGN KEY (multimedia_id) REFERENCES Multimedia(id)
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT fk_mm_mundial 
        FOREIGN KEY (mundial_id) REFERENCES Mundial(ID_MUNDIAL)
        ON DELETE CASCADE ON UPDATE CASCADE
);


SELECT * FROM MUNDIAL;
INSERT INTO Multimedia_mundial (multimedia_id, mundial_id, es_copa)
VALUES (LAST_INSERT_ID(), 6, 1);


USE WTC;


ALTER TABLE publicacion
rename column ID_PUBLICACION to id;

ALTER TABLE likes
DROP foreign key likes_ibfk_2;

CREATE TABLE mundial (
  id int(11) NOT NULL AUTO_INCREMENT,
  anio year(4) NOT NULL,
  titulo varchar(100) NOT NULL,
  descripcion text DEFAULT NULL,
  equipos text DEFAULT NULL,
  formato text DEFAULT NULL,
  estadios text DEFAULT NULL,
  partidos text DEFAULT NULL,
  estadisticas text DEFAULT NULL,
  entrevistas text DEFAULT NULL,
  incidentes text DEFAULT NULL,
  polemicas text DEFAULT NULL,
  jugadas text DEFAULT NULL,
  CreadoAdmin int(11) DEFAULT NULL,
  ModificadoAdmin int(11) DEFAULT NULL,
  detalles longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(detalles)),
  PRIMARY KEY (id),
  KEY mundial_ibfk_1 (CreadoAdmin),
  KEY mundial_ibfk_2 (ModificadoAdmin),
  CONSTRAINT mundial_ibfk_1 FOREIGN KEY (CreadoAdmin) REFERENCES usuario (ID_USUARIO),
  CONSTRAINT mundial_ibfk_2 FOREIGN KEY (ModificadoAdmin) REFERENCES usuario (ID_USUARIO)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


ALTER TABLE publicacion
CHANGE COLUMN CONTENIDO descripcion TEXT;
ALTER TABLE publicacion
CHANGE COLUMN CATEGORIA categoria_id INT;
ALTER TABLE publicacion
CHANGE COLUMN MUNDIAL mundial_id INT;
ALTER TABLE publicacion
CHANGE COLUMN USUARIO autor_id INT NOT NULL;
ALTER TABLE publicacion
ADD COLUMN AprobadoAdmin INT NULL AFTER autor_id;
ALTER TABLE publicacion
MODIFY COLUMN titulo VARCHAR(150) NOT NULL;
ALTER TABLE publicacion
MODIFY COLUMN fecha_publicacion DATETIME DEFAULT CURRENT_TIMESTAMP();
UPDATE publicacion
SET ESTATUS = 
    CASE
        WHEN ESTATUS = 'APROBADA' THEN 'aprobada'
        WHEN ESTATUS = 'RECHAZADA' THEN 'rechazada'
        ELSE 'pendiente'
    END
WHERE id > 0;

ALTER TABLE publicacion
MODIFY COLUMN ESTATUS 
    ENUM('pendiente','aprobada','rechazada') 
    DEFAULT 'pendiente';
ALTER TABLE publicacion DROP FOREIGN KEY publicacion_ibfk_1;
ALTER TABLE publicacion DROP FOREIGN KEY publicacion_ibfk_2;

ALTER TABLE publicacion
ADD CONSTRAINT publicacion_ibfk_2 FOREIGN KEY (mundial_id) REFERENCES mundial(id) ON DELETE SET NULL ON UPDATE CASCADE;


CREATE TABLE categorias (
  id int(11) NOT NULL AUTO_INCREMENT,
  nombre varchar(100) NOT NULL,
  CreadoAdmin int(11) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY categorias_ibfk_1 (CreadoAdmin),
  CONSTRAINT categorias_ibfk_1 FOREIGN KEY (CreadoAdmin) REFERENCES usuario (ID_USUARIO)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


DROP TABLE IF EXISTS sede;

CREATE TABLE sede (
  id int(11) NOT NULL AUTO_INCREMENT,
  mundial_id int(11) NOT NULL,
  sede_id int(11) NOT NULL,
  PRIMARY KEY (id),
  KEY mundial_id (mundial_id),
  KEY sede_id (sede_id),
  CONSTRAINT sede_ibfk_1 FOREIGN KEY (mundial_id) REFERENCES mundial (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT sede_ibfk_2 FOREIGN KEY (sede_id) REFERENCES pais (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

ALTER TABLE mundial
RENAME COLUMN ID_MUNDIAL TO id;


DROP TABLE IF EXISTS multimedia_mundial;

CREATE TABLE multimedia_mundial (
  id int(11) NOT NULL AUTO_INCREMENT,
  multimedia_id int(11) NOT NULL,
  mundial_id int(11) NOT NULL,
  es_banner tinyint(1) NOT NULL DEFAULT 0 COMMENT '1 si es el banner principal, 0 si es de la galeria',
  es_copa tinyint(1) NOT NULL DEFAULT 0,
  es_mascota tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY multimedia_id (multimedia_id),
  KEY mundial_id (mundial_id),
  CONSTRAINT multimedia_mundial_ibfk_1 FOREIGN KEY (multimedia_id) REFERENCES multimedia (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT multimedia_mundial_ibfk_2 FOREIGN KEY (mundial_id) REFERENCES mundial (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;



DROP TABLE IF EXISTS multimedia_publicacion;

CREATE TABLE multimedia_publicacion (
  id int(11) NOT NULL AUTO_INCREMENT,
  estatus tinyint(4) DEFAULT 1,
  multimedia_id int(11) NOT NULL,
  publicacion_id int(11) NOT NULL,
  PRIMARY KEY (id),
  KEY multimedia_id (multimedia_id),
  KEY publicacion_id (publicacion_id),
  CONSTRAINT multimedia_publicacion_ibfk_1 FOREIGN KEY (multimedia_id) REFERENCES multimedia (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT multimedia_publicacion_ibfk_2 FOREIGN KEY (publicacion_id) REFERENCES publicacion (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


