CREATE DATABASE WTC;

USE WTC;

CREATE TABLE USUARIO (
ID_USUARIO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOMBRES VARCHAR (20) NOT NULL,
APELLIDO_P VARCHAR (20) NOT NULL,
APELLIDO_M VARCHAR (20) NOT NULL,
NACIMIENTO DATE  NOT NULL,
GENERO ENUM ('M', 'F') NOT NULL,
NACIONALIDAD VARCHAR (20) NOT NULL,
PAIS_ORIGEN VARCHAR (20) NOT NULL,
CORREO VARCHAR (30) NOT NULL,
CONTRASENNA VARCHAR (30) NOT NULL,
TIPO_USUARIO ENUM ('ADMIN','USUARIO') NOT NULL
);

CREATE TABLE MULTIMEDIA (
ID_MULTIMEDIA INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
ARCHIVO BLOB NOT NULL

);

CREATE TABLE MUNDIAL(
ID_MUNDIAL INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR (50) NOT NULL,
ANNO VARCHAR (10) NOT NULL,
SEDE VARCHAR (50) NOT NULL,
DESCRIPCION TEXT NOT NULL,
LOGO BLOB NOT NULL,
MASCOTA_NOMBRE VARCHAR (30) NOT NULL,
MASCOTA_IMAGEN BLOB NOT NULL

);

USE WTC;


CREATE TABLE CATEGORIA (
ID_CATEGORIA INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR (30) NOT NULL

);

CREATE TABLE PUBLICACION (
ID_PUBLICACION INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
TITULO VARCHAR (50) NOT NULL,
CONTENIDO TEXT NOT NULL,
FECHA_APROBACION DATE NOT NULL,
FECHA_PUBLICACION DATE NOT NULL,
ESTATUS ENUM ('APROBADA', 'RECHAZADA'),
MULTIMEDIA INT,
USUARIO INT,
MUNDIAL INT,
CATEGORIA INT,

FOREIGN KEY (USUARIO) REFERENCES USUARIO (ID_USUARIO),
FOREIGN KEY (MULTIMEDIA) REFERENCES MULTIMEDIA (ID_MULTIMEDIA),
FOREIGN KEY (MUNDIAL) REFERENCES MUNDIAL  (ID_MUNDIAL),
FOREIGN KEY (CATEGORIA) REFERENCES CATEGORIA (ID_CATEGORIA)
);

CREATE TABLE COMENTARIOS (
ID_COMENTARIO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
CONTENIDO TEXT NOT NULL,
USUARIO INT NOT NULL,
PUBLICACION INT NOT NULL,

FOREIGN KEY (USUARIO) REFERENCES USUARIO (ID_USUARIO),
FOREIGN KEY (PUBLICACION) REFERENCES PUBLICACION (ID_PUBLICACION)
);


CREATE TABLE LIKES (
USUARIO INT NOT NULL,
PUBLICACION INT NOT NULL,

FOREIGN KEY (USUARIO) REFERENCES USUARIO (ID_USUARIO),
FOREIGN KEY (PUBLICACION) REFERENCES PUBLICACION (ID_PUBLICACION),
PRIMARY KEY (USUARIO, PUBLICACION)

);

USE WTC;
CREATE TABLE MUNDIAL_EQUIPOS (
    ID_MUNDIAL INT NOT NULL,
    ID_EQUIPO INT NOT NULL,
    PRIMARY KEY (ID_MUNDIAL, ID_EQUIPO),
    FOREIGN KEY (ID_MUNDIAL) REFERENCES MUNDIAL(ID_MUNDIAL),
    FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO)
);
CREATE TABLE EQUIPO (
    ID_EQUIPO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE
);

SELECT * FROM USUARIO;
USE WTC;
ALTER TABLE USUARIO
ADD COLUMN IMAGEN_PERFIL LONGBLOB NULL 
AFTER CONTRASENNA;

INSERT INTO Multimedia_mundial (multimedia_id, mundial_id, es_copa)
VALUES (LAST_INSERT_ID(), 6, 1);

CREATE TABLE multimedia_mundial (
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    multimedia_id INT(11) NOT NULL,
    mundial_id INT(11) NOT NULL,
    es_banner TINYINT(1) DEFAULT 0,
    es_copa TINYINT(1) DEFAULT 0,
    es_mascota TINYINT(1) DEFAULT 0,

    CONSTRAINT fk_mm_multimedia 
        FOREIGN KEY (multimedia_id) REFERENCES Multimedia(id)
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT fk_mm_mundial 
        FOREIGN KEY (mundial_id) REFERENCES Mundial(id)
        ON DELETE CASCADE ON UPDATE CASCADE
);